name: Auto deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch the whole history to prevent unrelated history errors
        fetch-depth: '0'
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: jetli/trunk-action@v0.4.0
    
    - name: Test
      run: cargo test --verbose -p backend
    - name: Build
      run: trunk build frontend/index.html
      
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch the whole history to prevent unrelated history errors
        fetch-depth: '0'
    
    - name: Merge Fast Forward
      uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
      with:
        # Branch to merge
        branchtomerge: main
        # Branch that will be updated
        branch: deploy  
