name: Test pull request

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jetli/trunk-action@v0.4.0
    
    - name: Test
      run: cargo test --verbose -p catered-backend
    - name: Build
      run: trunk build frontend/index.html
      
      